name: mypcernet
channels:
  - open3d-admin
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - attrs=22.1.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2022.12.7
  - cffi=1.15.1
  - conda-pack=0.6.0
  - cudatoolkit=11.1.74
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - ffmpeg=4.3
  - freetype=2.11.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - icu=58.2
  - importlib_metadata=4.11.3
  - importlib_resources=5.2.0
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jupyter_client=7.4.9
  - jupyter_core=4.11.2
  - jupyter_server=1.23.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.8
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libllvm11=11.1.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxml2=2.9.14
  - libxslt=1.1.35
  - llvmlite=0.38.0
  - lxml=4.9.1
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - numba=0.55.1
  - numpy=1.20.3
  - numpy-base=1.20.3
  - open3d=0.11.2
  - openh264=2.1.1
  - openssl=1.1.1w
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.1.2
  - pkgutil-resolve-name=1.3.10
  - prometheus_client=0.14.1
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pykdtree=1.3.4
  - python=3.7.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - pytorch=1.10.1
  - pytorch-mutex=1.0
  - readline=8.1.2
  - send2trash=1.8.0
  - six=1.16.0
  - soupsieve=2.3.2.post1
  - sqlite=3.39.2
  - tbb=2021.5.0
  - tk=8.6.12
  - torchvision=0.11.2
  - tornado=6.2
  - typing_extensions=4.3.0
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - absl-py==1.2.0
    - addict==2.4.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - anyio==3.6.1
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - babel==2.10.3
    - bleach==5.0.1
    - cached-property==1.5.2
    - cachetools==5.2.0
    - ccimport==0.4.1
    - charset-normalizer==2.1.1
    - click==8.1.3
    - configobj==5.0.6
    - cumm-cu114==0.3.4
    - cycler==0.11.0
    - cython==0.29.28
    - debugpy==1.6.3
    - deprecation==2.1.0
    - docker-pycreds==0.4.0
    - easydict==1.9
    - fastjsonschema==2.16.1
    - filelock==3.8.0
    - fire==0.4.0
    - fonttools==4.37.1
    - frozenlist==1.3.1
    - gdown==4.5.1
    - geomdl==5.3.1
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.11.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.48.1
    - h5py==3.6.0
    - idna==3.3
    - imageio==2.21.2
    - importlib-metadata==4.12.0
    - importlib-resources==5.9.0
    - ipdb==0.13.9
    - ipython==7.34.0
    - ipywidgets==8.0.2
    - joblib==1.1.0
    - json5==0.9.10
    - jsonschema==4.15.0
    - jupyter-client==7.3.5
    - jupyter-core==4.11.1
    - jupyter-packaging==0.12.3
    - jupyter-server==1.18.1
    - jupyterlab==3.4.6
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.15.1
    - jupyterlab-widgets==3.0.3
    - kiwisolver==1.4.4
    - lap==0.4.0
    - lapsolver==1.1.0
    - lark==1.1.3
    - laspy==2.4.1
    - markdown==3.4.1
    - matplotlib==3.5.1
    - mistune==2.0.4
    - multidict==6.0.2
    - multimethod==1.7
    - munch==2.5.0
    - nbclassic==0.4.3
    - nbclient==0.6.7
    - nbconvert==7.0.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - ninja==1.10.2.3
    - notebook==6.4.12
    - notebook-shim==0.1.0
    - oauthlib==3.2.0
    - opencv-python==4.6.0.66
    - packaging==21.3
    - pandas==1.3.5
    - pathtools==0.1.2
    - pccm==0.4.2
    - plyfile==0.9
    - pointnet2-cuda==0.0.0
    - pointops==0.0.0
    - portalocker==2.5.1
    - positional-encodings==6.0.1
    - pptk==0.1.0
    - promise==2.3
    - prompt-toolkit==3.0.31
    - protobuf==3.19.4
    - psutil==5.9.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybind11==2.10.0
    - pygments==2.13.0
    - pymeshlab==2022.2.post2
    - pyparsing==3.0.9
    - pyquaternion==0.9.9
    - pyrsistent==0.18.1
    - pysocks==1.7.1
    - pytz==2022.2.1
    - pyvista==0.33.2
    - pyyaml==6.0
    - pyzmq==23.2.1
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - scooby==0.6.0
    - sentry-sdk==1.9.7
    - setuptools==65.3.0
    - shortuuid==1.0.9
    - smmap==5.0.0
    - sniffio==1.3.0
    - spconv-cu114==2.2.3
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-logger==0.1.0
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - termcolor==1.1.0
    - termcolor-whl==1.1.2
    - terminado==0.15.0
    - thop==0.1.1-2209072238
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - toml==0.10.2
    - tomlkit==0.11.4
    - torch-scatter==2.0.9
    - torchsummary==1.5.1
    - tqdm==4.62.3
    - traitlets==5.3.0
    - transforms3d==0.4.1
    - trimesh==3.14.1
    - urllib3==1.26.12
    - vtk==9.1.0
    - wandb==0.12.10
    - webencodings==0.5.1
    - websocket-client==1.4.1
    - werkzeug==2.2.2
    - widgetsnbextension==4.0.3
    - wslink==1.8.2
    - yarl==1.8.1
    - yaspin==2.2.0
    - zipp==3.8.1

